// Database schema definition
// Table: experiment_sessions
export const experimentSessionsSchema = {
  tableName: 'experiment_sessions',
  columns: {
    id: 'SERIAL PRIMARY KEY',
    created_at: 'TIMESTAMPTZ DEFAULT NOW()',
    q1: 'INTEGER',
    q2: 'INTEGER',
    q3: 'INTEGER',
    q4: 'INTEGER',
    q5: 'INTEGER',
    q6: 'INTEGER',
    q7: 'INTEGER',
    name: 'TEXT',
    gender: 'TEXT',
    age: 'TEXT',
    phone: 'TEXT',
    education: 'TEXT',
    has_license: 'TEXT',
    driving_years: 'TEXT',
    driving_km: 'TEXT',
    has_assist_drive: 'TEXT',
    q9: 'INTEGER',
    q10: 'INTEGER',
    q11: 'INTEGER',
    q12: 'INTEGER',
    q13: 'INTEGER',
    q14: 'INTEGER',
    q15: 'INTEGER',
    q16: 'INTEGER',
    q17: 'INTEGER',
    scenario_order: 'TEXT',
    scenario_a_decision: 'TEXT',
    scenario_a_accept_self: 'INTEGER',
    scenario_a_accept_public: 'INTEGER',
    scenario_a_manipulation: 'TEXT',
    scenario_b_decision: 'TEXT',
    scenario_b_accept_self: 'INTEGER',
    scenario_b_accept_public: 'INTEGER',
    scenario_b_manipulation: 'TEXT',
  },
};
